site_title = "ArxivDaily"
limit_days = 7
cache_url = "https://XqZeppelinhead0702.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.SD"
title = "Sound"

[[sources]]
limit = 150
category = "eess.AS"
title = "Speech Processing"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
